// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Tag': string;
  'blue': string;
  'closable': string;
  'common': string;
  'cyan': string;
  'dashed': string;
  'default': string;
  'geekBlue': string;
  'gold': string;
  'green': string;
  'large': string;
  'lime': string;
  'magenta': string;
  'new': string;
  'orange': string;
  'purple': string;
  'red': string;
  'small': string;
  'volcano': string;
}
export const cssExports: CssExports;
export default cssExports;
