// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  Tag: string;
  blue: string;
  closable: string;
  cyan: string;
  dashed: string;
  default: string;
  geekBlue: string;
  gold: string;
  green: string;
  lime: string;
  magenta: string;
  new: string;
  orange: string;
  purple: string;
  red: string;
  volcano: string;
  common: string;
  small: string;
  large: string;
}
export const cssExports: CssExports;
export default cssExports;
