// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'danger': string;
  'dashed': string;
  'default': string;
  'ghost': string;
  'large': string;
  'link': string;
  'primary': string;
  'small': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
