// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'menu': string;
  'menu-item': string;
  'menu-subitem': string;
  'menu-submenu': string;
  'menu-title': string;
}
export const cssExports: CssExports;
export default cssExports;
