// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Text': string;
  'danger': string;
  'delete': string;
  'disabled': string;
  'editable': string;
  'italic': string;
  'mark': string;
  'primary': string;
  'secondary': string;
  'strong': string;
  'success': string;
  'underline': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
