// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Tabs': string;
  'active': string;
  'body': string;
  'header': string;
  'tab': string;
}
export const cssExports: CssExports;
export default cssExports;
