// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Switch': string;
  'active': string;
  'disabled': string;
  'handle': string;
}
export const cssExports: CssExports;
export default cssExports;
