// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'TreeSelect': string;
  'item': string;
  'list': string;
  'listContainer': string;
  'toggle': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
