// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Autocomplete': string;
  'itemsList': string;
  'noResultsLi': string;
}
export const cssExports: CssExports;
export default cssExports;
