// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Badge': string;
  'basic': string;
  'blue': string;
  'cyan': string;
  'default': string;
  'dot': string;
  'error': string;
  'green': string;
  'magenta': string;
  'processing': string;
  'purple': string;
  'red': string;
  'ribbon': string;
  'round': string;
  'small': string;
  'status': string;
  'success': string;
  'text': string;
  'volcano': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
